version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    hostname: "keycloak"
    command: ["-Djboss.http.port=8081 -Djboss.https.port=8082"]
    ports:
      - 8081:8081
      - 8082:8082
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8081/auth
      - KEYCLOAK_IMPORT=/tmp/demo-local-realm.json
    volumes:
      - ./keycloak/demo-local-realm.json:/tmp/demo-local-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8081/auth/realms/demo-local/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 5

  demo-app:
    image: michaelruocco/camunda-spring-boot-demo:${APP_VERSION}
    container_name: demo-app
    restart: on-failure
    ports:
      - 8083:80
    environment:
      - SERVER_PORT=80
      - AUTH_SERVER_HTTP=http://keycloak:8081
      - AUTH_SERVER_HTTPS=https://keycloak:8082
      - AUTH_REALM=demo-local
      - AUTH_CLIENT_ID=demo-client-id
      - AUTH_CLIENT_SECRET=demo-client-secret
      - AUTH_ADMIN_GROUP=camunda-admin
    depends_on:
      - keycloak