version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
      - KEYCLOAK_IMPORT=/tmp/demo-realm.json
    volumes:
      - ./keycloak/demo-realm.json:/tmp/demo-realm.json

  demo-app:
    image: michaelruocco/camunda-spring-boot-demo:${APP_VERSION}
    container_name: demo-app
    ports:
      - 8082:80
    environment:
      - SERVER_PORT=80
      - AUTH_SERVER_URL=http://keycloak:8080/auth
      - AUTH_REALM=demo-local
      - AUTH_CLIENT_ID=demo-client-id
      - AUTH_CLIENT_SECRET=demo-client-secret
    depends_on:
      - keycloak