version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    hostname: "keycloak"
    command: ["-Djboss.http.port=8091", "-Djboss.https.port=8092"]
    ports:
      - 8091:8091
      - 8092:8092
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8091/auth
      - KEYCLOAK_IMPORT=/tmp/demo-local-realm.json
    volumes:
      - ./keycloak/demo-local-realm.json:/tmp/demo-local-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8091/auth/realms/demo-local/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 5

  wiremock:
    image: wiremock/wiremock:2.31.0-alpine
    container_name: wiremock
    command: ["--global-response-templating"]
    ports:
      - 8093:8080
    volumes:
      - ./wiremock:/home/wiremock

  aws-services:
    image: localstack/localstack:latest
    container_name: aws-services
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - DEFAULT_REGION=eu-west-2
      - SERVICES=s3

  demo-app:
    image: michaelruocco/camunda-spring-boot-demo:${APP_VERSION}
    container_name: demo-app
    restart: on-failure
    ports:
      - 8090:80
    environment:
      - SERVER_PORT=80
      - AUTH_SERVER_HTTP=http://keycloak:8091
      - AUTH_SERVER_HTTPS=https://keycloak:8092
      - AUTH_REALM=demo-local
      - AUTH_CLIENT_ID=demo-client-id
      - AUTH_CLIENT_SECRET=demo-client-secret
      - AUTH_ADMIN_GROUP=camunda-admin
      - QUOTE_HOST=http://wiremock:8080
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - AWS_REGION=eu-west-2
      - AWS_S3_PAYMENT_BUCKET_NAME=demo-payment
      - AWS_S3_ENDPOINT_OVERRIDE=http://aws-services:4566
    depends_on:
      - wiremock
      - keycloak