camunda.bpm:
  authorization:
    enabled: true
  filter:
    create: All
  webapp.application-path:

server.servlet.context-path: /camunda

spring:
  jersey:
    application-path: /engine-rest

logging.level.org.springframework.security: DEBUG