version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    command: ["-Djboss.http.port=8091", "-Djboss.https.port=8092"]
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-local-realm.json
    volumes:
      - ../../../keycloak/demo-local-realm.json:/tmp/demo-local-realm.json
      - ../../../keycloak/certs:/etc/x509/https

  wiremock:
    image: wiremock/wiremock:2.31.0-alpine
    command: ["--global-response-templating"]
    volumes:
      - ../../../wiremock:/home/wiremock

  aws-services:
    image: localstack/localstack:latest
    volumes:
      - ../../../localstack:/docker-entrypoint-initaws.d
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - DEFAULT_REGION=eu-west-2
      - SERVICES=s3

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CREATE_TOPICS=payment-topic:1:1
    depends_on:
      - zookeeper